---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Jakob Voß"
title: "Wikidata als Universalbibliographie"
abstract: "..."
urn:
date: "2016-XX-XX"
comments: false
sharing: true
footer: true
...
