---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Jakob Voß"
title: "Wikidata als Universalbibliographie. Ein Exposé"
abstract: "..."
urn:
date: 
comments: false
sharing: true
footer: true
...
